### Problem Statement:
* This dataset helps improve FedEx Logistics’ global supply chain by showing details about purchase orders, shipping methods, vendor agreements, and delivery schedules.
* As eCommerce grows and shipments increase worldwide, analyzing this data can find delays, lower shipping costs, and make deliveries faster.
* The goal is to make operations smoother, keep customers happy, and deliver packages on time while saving costs.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import statistics as stats

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv(r"D:\python\FedEx Logistic\SCMS_Delivery_History_Dataset.csv")

In [4]:
df.head()

,ID,Project Code,PQ #,PO / SO #,ASN/DN #,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,...,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,1,100-CI-T01,Pre-PQ Process,SCMS-4,ASN-8,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,...,30,19,551.0,29.00,0.97,Ranbaxy Fine Chemicals LTD,Yes,13,780.34,NaN
1,3,108-VN-T01,Pre-PQ Process,SCMS-13,ASN-85,Vietnam,PMO - US,Direct Drop,EXW,Air,...,240,1000,6200.0,6.20,0.03,"Aurobindo Unit III, India",Yes,358,4521.5,NaN
2,4,100-CI-T01,Pre-PQ Process,SCMS-20,ASN-14,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,...,100,500,40000.0,80.00,0.80,ABBVIE GmbH & Co.KG Wiesbaden,Yes,171,1653.78,NaN
3,15,108-VN-T01,Pre-PQ Process,SCMS-78,ASN-50,Vietnam,PMO - US,Direct Drop,EXW,Air,...,60,31920,127360.8,3.99,0.07,"Ranbaxy, Paonta Shahib, India",Yes,1855,16007.06,NaN
4,16,108-VN-T01,Pre-PQ Process,SCMS-81,ASN-55,Vietnam,PMO - US,Direct Drop,EXW,Air,...,60,38000,121600.0,3.20,0.05,"Aurobindo Unit III, India",Yes,7590,45450.08,NaN

In [5]:
df.tail()

,ID,Project Code,PQ #,PO / SO #,ASN/DN #,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,...,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
10319,86818,103-ZW-T30,FPQ-15197,SO-50020,DN-4307,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,...,60,166571,599655.60,3.60,0.06,"Mylan, H-12 & H-13, India",No,See DN-4307 (ID#:83920),See DN-4307 (ID#:83920),705.79
10320,86819,104-CI-T30,FPQ-15259,SO-50102,DN-4313,Côte d'Ivoire,PMO - US,From RDC,N/A - From RDC,Truck,...,60,21072,137389.44,6.52,0.11,Hetero Unit III Hyderabad IN,No,See DN-4313 (ID#:83921),See DN-4313 (ID#:83921),161.71
10321,86821,110-ZM-T30,FPQ-14784,SO-49600,DN-4316,Zambia,PMO - US,From RDC,N/A - From RDC,Truck,...,30,514526,5140114.74,9.99,0.33,Cipla Ltd A-42 MIDC Mahar. IN,No,Weight Captured Separately,Freight Included in Commodity Cost,5284.04
10322,86822,200-ZW-T30,FPQ-16523,SO-51680,DN-4334,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,...,60,17465,113871.80,6.52,0.11,Mylan (formerly Matrix) Nashik,Yes,1392,Freight Included in Commodity Cost,134.03
10323,86823,103-ZW-T30,FPQ-15197,SO-50022,DN-4336,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,...,60,36639,72911.61,1.99,0.03,"Cipla, Goa, India",No,Weight Captured Separately,Freight Included in Commodity Cost,85.82

# **1. Initial Data Exploration :**

#### In this step we going to:
1. Take a look at the list of columns in the Dataset
2. See shape of the dataset "the number of rows and columns"
3. Check the variable type of each column
4. Check for null values
5. Check for duplicate records

In [6]:
df.columns

Index(['ID', 'Project Code', 'PQ #', 'PO / SO #', 'ASN/DN #', 'Country',
       'Managed By', 'Fulfill Via', 'Vendor INCO Term', 'Shipment Mode',
       'PQ First Sent to Client Date', 'PO Sent to Vendor Date',
       'Scheduled Delivery Date', 'Delivered to Client Date',
       'Delivery Recorded Date', 'Product Group', 'Sub Classification',
       'Vendor', 'Item Description', 'Molecule/Test Type', 'Brand', 'Dosage',
       'Dosage Form', 'Unit of Measure (Per Pack)', 'Line Item Quantity',
       'Line Item Value', 'Pack Price', 'Unit Price', 'Manufacturing Site',
       'First Line Designation', 'Weight (Kilograms)', 'Freight Cost (USD)',
       'Line Item Insurance (USD)'],
      dtype='object')

In [7]:
print("rows :",df.shape[0])
print("columns :",df.shape[1])

rows : 10324
columns : 33

In [8]:
df.shape

(10324, 33)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10324 entries, 0 to 10323
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            10324 non-null  int64
 1   Project Code                  10324 non-null  object
 2   PQ #                          10324 non-null  object
 3   PO / SO #                     10324 non-null  object
 4   ASN/DN #                      10324 non-null  object
 5   Country                       10324 non-null  object
 6   Managed By                    10324 non-null  object
 7   Fulfill Via                   10324 non-null  object
 8   Vendor INCO Term              10324 non-null  object
 9   Shipment Mode                 9964 non-null   object
 10  PQ First Sent to Client Date  10324 non-null  object
 11  PO Sent to Vendor Date        10324 non-null  object
 12  Scheduled Delivery Date       10324 non-null  object
 13  Delivered to Client Date      10324 non-null  object
 14  Delivery Recorded Date        10324 non-null  object
 15  Product Group                 10324 non-null  object
 16  Sub Classification            10324 non-null  object
 17  Vendor                        10324 non-null  object
 18  Item Description              10324 non-null  object
 19  Molecule/Test Type            10324 non-null  object
 20  Brand                         10324 non-null  object
 21  Dosage                        8588 non-null   object
 22  Dosage Form                   10324 non-null  object
 23  Unit of Measure (Per Pack)    10324 non-null  int64
 24  Line Item Quantity            10324 non-null  int64
 25  Line Item Value               10324 non-null  float64
 26  Pack Price                    10324 non-null  float64
 27  Unit Price                    10324 non-null  float64
 28  Manufacturing Site            10324 non-null  object
 29  First Line Designation        10324 non-null  object
 30  Weight (Kilograms)            10324 non-null  object
 31  Freight Cost (USD)            10324 non-null  object
 32  Line Item Insurance (USD)     10037 non-null  float64
dtypes: float64(4), int64(3), object(26)
memory usage: 2.6+ MB

In [10]:
df.isnull().sum()

ID                                 0
Project Code                       0
PQ #                               0
PO / SO #                          0
ASN/DN #                           0
Country                            0
Managed By                         0
Fulfill Via                        0
Vendor INCO Term                   0
Shipment Mode                    360
PQ First Sent to Client Date       0
PO Sent to Vendor Date             0
Scheduled Delivery Date            0
Delivered to Client Date           0
Delivery Recorded Date             0
Product Group                      0
Sub Classification                 0
Vendor                             0
Item Description                   0
Molecule/Test Type                 0
Brand                              0
Dosage                          1736
Dosage Form                        0
Unit of Measure (Per Pack)         0
Line Item Quantity                 0
Line Item Value                    0
Pack Price                         0
Unit Price                         0
Manufacturing Site                 0
First Line Designation             0
Weight (Kilograms)                 0
Freight Cost (USD)                 0
Line Item Insurance (USD)        287
dtype: int64

In [11]:
df.isnull().mean()*100

ID                               0.000000
Project Code                     0.000000
PQ #                             0.000000
PO / SO #                        0.000000
ASN/DN #                         0.000000
Country                          0.000000
Managed By                       0.000000
Fulfill Via                      0.000000
Vendor INCO Term                 0.000000
Shipment Mode                    3.487021
PQ First Sent to Client Date     0.000000
PO Sent to Vendor Date           0.000000
Scheduled Delivery Date          0.000000
Delivered to Client Date         0.000000
Delivery Recorded Date           0.000000
Product Group                    0.000000
Sub Classification               0.000000
Vendor                           0.000000
Item Description                 0.000000
Molecule/Test Type               0.000000
Brand                            0.000000
Dosage                          16.815188
Dosage Form                      0.000000
Unit of Measure (Per Pack)       0.000000
Line Item Quantity               0.000000
Line Item Value                  0.000000
Pack Price                       0.000000
Unit Price                       0.000000
Manufacturing Site               0.000000
First Line Designation           0.000000
Weight (Kilograms)               0.000000
Freight Cost (USD)               0.000000
Line Item Insurance (USD)        2.779930
dtype: float64

In [12]:
df.describe()

,ID,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Line Item Insurance (USD)
count,10324.000000,10324.000000,10324.000000,1.032400e+04,10324.000000,10324.000000,10037.000000
mean,51098.968229,77.990895,18332.534870,1.576506e+05,21.910241,0.611701,240.117626
std,31944.332496,76.579764,40035.302961,3.452921e+05,45.609223,3.275808,500.190568
min,1.000000,1.000000,1.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,12795.750000,30.000000,408.000000,4.314593e+03,4.120000,0.080000,6.510000
50%,57540.500000,60.000000,3000.000000,3.047147e+04,9.300000,0.160000,47.040000
75%,83648.250000,90.000000,17039.750000,1.664471e+05,23.592500,0.470000,252.400000
max,86823.000000,1000.000000,619999.000000,5.951990e+06,1345.640000,238.650000,7708.440000

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.isnull().mean()*100

ID                               0.000000
Project Code                     0.000000
PQ #                             0.000000
PO / SO #                        0.000000
ASN/DN #                         0.000000
Country                          0.000000
Managed By                       0.000000
Fulfill Via                      0.000000
Vendor INCO Term                 0.000000
Shipment Mode                    3.487021
PQ First Sent to Client Date     0.000000
PO Sent to Vendor Date           0.000000
Scheduled Delivery Date          0.000000
Delivered to Client Date         0.000000
Delivery Recorded Date           0.000000
Product Group                    0.000000
Sub Classification               0.000000
Vendor                           0.000000
Item Description                 0.000000
Molecule/Test Type               0.000000
Brand                            0.000000
Dosage                          16.815188
Dosage Form                      0.000000
Unit of Measure (Per Pack)       0.000000
Line Item Quantity               0.000000
Line Item Value                  0.000000
Pack Price                       0.000000
Unit Price                       0.000000
Manufacturing Site               0.000000
First Line Designation           0.000000
Weight (Kilograms)               0.000000
Freight Cost (USD)               0.000000
Line Item Insurance (USD)        2.779930
dtype: float64

In [15]:
df.describe()

,ID,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Line Item Insurance (USD)
count,10324.000000,10324.000000,10324.000000,1.032400e+04,10324.000000,10324.000000,10037.000000
mean,51098.968229,77.990895,18332.534870,1.576506e+05,21.910241,0.611701,240.117626
std,31944.332496,76.579764,40035.302961,3.452921e+05,45.609223,3.275808,500.190568
min,1.000000,1.000000,1.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,12795.750000,30.000000,408.000000,4.314593e+03,4.120000,0.080000,6.510000
50%,57540.500000,60.000000,3000.000000,3.047147e+04,9.300000,0.160000,47.040000
75%,83648.250000,90.000000,17039.750000,1.664471e+05,23.592500,0.470000,252.400000
max,86823.000000,1000.000000,619999.000000,5.951990e+06,1345.640000,238.650000,7708.440000

# **2 .Data Cleaning :**
* Feature Selection
* Handling missing values
* Removing duplicates
* Fixing data types
* Standardizing categorical data
* Handle Outliers

## 1. Feature Selection

* Feature selection is the process of choosing the most relevant variables (columns/features) from a dataset and removing the unnecessary ones.

In [16]:
ex_df = df[[
    'Country',
    'Managed By',
    'Fulfill Via',
    'Shipment Mode',
    'PQ First Sent to Client Date',
    'PO Sent to Vendor Date',
    'Scheduled Delivery Date',
    'Delivered to Client Date',
    'Delivery Recorded Date',
    'Line Item Quantity',
    'Line Item Value',
    'Weight (Kilograms)',
    'Freight Cost (USD)',
    'Vendor',
    'Line Item Insurance (USD)'
]]

In [17]:
ex_df

,Country,Managed By,Fulfill Via,Shipment Mode,PQ First Sent to Client Date,PO Sent to Vendor Date,Scheduled Delivery Date,Delivered to Client Date,Delivery Recorded Date,Line Item Quantity,Line Item Value,Weight (Kilograms),Freight Cost (USD),Vendor,Line Item Insurance (USD)
0,Côte d'Ivoire,PMO - US,Direct Drop,Air,Pre-PQ Process,Date Not Captured,2-Jun-06,2-Jun-06,2-Jun-06,19,551.00,13,780.34,RANBAXY Fine Chemicals LTD.,NaN
1,Vietnam,PMO - US,Direct Drop,Air,Pre-PQ Process,Date Not Captured,14-Nov-06,14-Nov-06,14-Nov-06,1000,6200.00,358,4521.5,Aurobindo Pharma Limited,NaN
2,Côte d'Ivoire,PMO - US,Direct Drop,Air,Pre-PQ Process,Date Not Captured,27-Aug-06,27-Aug-06,27-Aug-06,500,40000.00,171,1653.78,Abbott GmbH & Co. KG,NaN
3,Vietnam,PMO - US,Direct Drop,Air,Pre-PQ Process,Date Not Captured,1-Sep-06,1-Sep-06,1-Sep-06,31920,127360.80,1855,16007.06,SUN PHARMACEUTICAL INDUSTRIES LTD (RANBAXY LAB...,NaN
4,Vietnam,PMO - US,Direct Drop,Air,Pre-PQ Process,Date Not Captured,11-Aug-06,11-Aug-06,11-Aug-06,38000,121600.00,7590,45450.08,Aurobindo Pharma Limited,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10319,Zimbabwe,PMO - US,From RDC,Truck,10/16/14,N/A - From RDC,31-Jul-15,15-Jul-15,20-Jul-15,166571,599655.60,See DN-4307 (ID#:83920),See DN-4307 (ID#:83920),SCMS from RDC,705.79
10320,Côte d'Ivoire,PMO - US,From RDC,Truck,10/24/14,N/A - From RDC,31-Jul-15,6-Aug-15,7-Aug-15,21072,137389.44,See DN-4313 (ID#:83921),See DN-4313 (ID#:83921),SCMS from RDC,161.71
10321,Zambia,PMO - US,From RDC,Truck,8/12/14,N/A - From RDC,31-Aug-15,25-Aug-15,3-Sep-15,514526,5140114.74,Weight Captured Separately,Freight Included in Commodity Cost,SCMS from RDC,5284.04
10322,Zimbabwe,PMO - US,From RDC,Truck,7/1/15,N/A - From RDC,9-Sep-15,4-Aug-15,11-Aug-15,17465,113871.80,1392,Freight Included in Commodity Cost,SCMS from RDC,134.03
10323,Zimbabwe,PMO - US,From RDC,Truck,10/16/14,N/A - From RDC,31-Aug-15,4-Aug-15,11-Aug-15,36639,72911.61,Weight Captured Separately,Freight Included in Commodity Cost,SCMS from RDC,85.82

In [18]:
ex_df.shape

(10324, 15)

In [19]:
ex_df.isnull().mean() * 100

Country                         0.000000
Managed By                      0.000000
Fulfill Via                     0.000000
Shipment Mode                   3.487021
PQ First Sent to Client Date    0.000000
PO Sent to Vendor Date          0.000000
Scheduled Delivery Date         0.000000
Delivered to Client Date        0.000000
Delivery Recorded Date          0.000000
Line Item Quantity              0.000000
Line Item Value                 0.000000
Weight (Kilograms)              0.000000
Freight Cost (USD)              0.000000
Vendor                          0.000000
Line Item Insurance (USD)       2.779930
dtype: float64

In [20]:
print("Missing=1:", df[df['Weight (Kilograms)']==1]['Weight (Kilograms)'].dropna().shape)
print("Missing=0:", df[df['Weight (Kilograms)']==0]['Weight (Kilograms)'].dropna().shape)

Missing=1: (0,)
Missing=0: (0,)

## 2. Handling missing values
* Handling missing values means identifying empty or null values in the dataset and replacing them with suitable values such as mean, median, or mode, or removing them if necessary. This step helps improve data quality and ensures accurate analysis.

In [21]:
shipment_mode = ex_df['Shipment Mode'].mode()[0]
ex_df['Shipment Mode'].fillna(shipment_mode, inplace=True)

* Shipment Mode is a categorical column and contains 3.48% missing values. Since it is a categorical variable, the missing values were imputed using the mode (most frequent value) of the column.

In [22]:
ex_df['Line Item Insurance (USD'] = ex_df['Line Item Insurance (USD)'].fillna(0)

* Line Item Insurance (USD) is a numerical column and contains 2.77% missing values. Since this column represents insurance cost, the missing values were imputed with 0, assuming that the shipments had no insurance cost.

In [23]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')

ex_df[['Freight Cost (USD)']] = imputer.fit_transform(
    ex_df[['Freight Cost (USD)']]
)

ValueError: Cannot use median strategy with non-numeric data:
could not convert string to float: 'Freight Included in Commodity Cost'

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')

ex_df[['Weight (Kilograms)']] = imputer.fit_transform(
    ex_df[['Weight (Kilograms)']]
)

In [ ]:
ex_df.columns

## 3. Removing duplicates

In [ ]:
ex_df.duplicated().sum()

In [ ]:
ex_df.drop_duplicates(inplace=True)

In [ ]:
ex_df.info()

## 4. Data Type Conversion :
* Data Type Conversion means converting columns into their correct data types, like changing numbers stored as text into numeric format or converting date columns into datetime format so the data can be analyzed correctly.

In [24]:
date_cols= ['PQ First Sent to Client Date', 'PO Sent to Vendor Date','Scheduled Delivery Date', 'Delivered to Client Date','Delivery Recorded Date']

for col in date_cols:
    ex_df[col]= pd.to_datetime(ex_df[col],errors='coerce')

In [25]:
numeric_cols= ['Line Item Quantity', 'Line Item Value','Weight (Kilograms)', 'Freight Cost (USD)','Line Item Insurance (USD)', 'Line Item Insurance (USD)']

for col in numeric_cols:
    ex_df[col] = pd.to_numeric(ex_df[col], errors='coerce')

## 5. Standardizing categorical data

In [ ]:
ex_df['Country'] = ex_df['Country'].str.strip().str.lower()

In [ ]:
ex_df.info()

## 6. Handle Outliers

In [ ]:
Q1 = ex_df['Line Item Value'].quantile(0.25)
Q3 = ex_df['Line Item Value'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# detect outliers
outliers = ex_df[(ex_df['Line Item Value'] < lower) | (ex_df['Line Item Value'] > upper)]
print("% Of Outlier :", len(outliers)/ len(ex_df['Line Item Value'])*100)

In [ ]:
clean_ex_df = ex_df.copy()

In [ ]:
clean_ex_df['Line Item Value'] = np.where(
    clean_ex_df['Line Item Value'] > upper, upper,
    np.where(clean_ex_df['Line Item Value'] < lower, lower, clean_ex_df['Line Item Value'])
)

* The dataset contained around 11% outliers, which is relatively high.
Instead of removing them and losing important shipment information, the outliers were capped using the IQR boundaries so that extreme values do not distort statistical analysis or machine learning models.

## Data Distribution After Outlier Handling

In [ ]:
plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
sns.histplot(ex_df['Line Item Value'], kde=True, bins=30)
plt.title("Before Outlier Handling")

plt.subplot(1,2,2)
sns.histplot(clean_ex_df['Line Item Value'], kde=True, bins=30)
plt.title("After Outlier Handling")

plt.tight_layout()
plt.show()

In [ ]:
Q1 = ex_df['Freight Cost (USD)'].quantile(0.25)
Q3 = ex_df['Freight Cost (USD)'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# detect outliers
outliers = ex_df[(ex_df['Freight Cost (USD)'] < lower) | (ex_df['Freight Cost (USD)'] > upper)]
print("% Of Outlier :", len(outliers)/ len(ex_df['Freight Cost (USD)'])*100)

In [ ]:
# remove

clean_ex_df['Line Item Value'] = np.where(
    clean_ex_df['Line Item Value'] > upper, upper,
    np.where(clean_ex_df['Line Item Value'] < lower, lower, clean_ex_df['Line Item Value'])
)

* The dataset contained around 3.75% outliers in the Freight Cost column, which is relatively low. Instead of keeping extreme values that could distort the analysis, these outliers were removed, as their small proportion does not significantly affect the dataset.

## Data Distribution After Outlier Handling

In [ ]:
plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
sns.boxplot(x=ex_df['Freight Cost (USD)'],showfliers=False)
plt.title("Before Outlier Handling")

plt.subplot(1,2,2)
sns.boxplot(x=clean_ex_df['Freight Cost (USD)'])
plt.title("After Outlier Handling")

plt.show()

In [ ]:
Q1 = ex_df['Weight (Kilograms)'].quantile(0.25)
Q3 = ex_df['Weight (Kilograms)'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# detect outliers
outliers = ex_df[(ex_df['Weight (Kilograms)'] < lower) | (ex_df['Weight (Kilograms)'] > upper)]
print("% Of Outlier :", len(outliers)/ len(ex_df['Weight (Kilograms)'])*100)

In [ ]:
clean_ex_df['Weight (Kilograms)'] = np.where(
    clean_ex_df['Weight (Kilograms)'] > upper, upper,
    np.where(clean_ex_df['Weight (Kilograms)'] < lower, lower, clean_ex_df['Weight (Kilograms)'])
)

* The dataset contained around 6% outliers in the Weight column, which is relatively high. Instead of removing them and losing important shipment information, the outliers were capped using the IQR boundaries so that extreme values do not distort statistical analysis or machine learning models.

## Data Distribution After Outlier Handling

In [ ]:
plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
sns.histplot(ex_df['Weight (Kilograms)'], kde=True)
plt.xlim(0,30000)
plt.title("Before Outlier Handling")

plt.subplot(1,2,2)
sns.histplot(clean_ex_df['Weight (Kilograms)'], kde=True)
plt.title("After Outlier Handling")

plt.tight_layout()
plt.show()

In [ ]:
ex_df.columns

# 3. Descriptive Statistics

* Descriptive statistics summarize data using numerical measures

#### i. Numerical Columns

In [ ]:
ex_df[['Freight Cost (USD)','Weight (Kilograms)','Line Item Value']].describe()

In [ ]:
clean_ex_df[['Freight Cost (USD)','Weight (Kilograms)','Line Item Value']].describe()

### Freight Cost (USD) :
* Before handling outliers, a few shipments had extremely high costs (up to 289,653), which made the average cost very high at around 11,076. The spread of the data was also very large, which didn’t reflect the majority of shipments. After handling outliers, the maximum cost dropped to 32,609, and the average reduced to about 8,015. This gives a better picture of what most shipments actually cost.

### Weight (Kilograms) :
* Initially, there were some shipments with extremely heavy weights (over 857,000 kg!), which pulled the average weight up to 3,432 kg. Most shipments were actually much lighter. After capping these outliers, the maximum weight dropped to 8,028 kg, and the average weight became 1,979 kg, which is much more realistic.

### Line Item Value :
* Some line items had extremely high values, reaching up to 5,951,990, which made the average value misleading at around 158,060. After removing/capping these extreme items, the maximum value became 32,624, and the average dropped to 22,820. Now, the data better reflects typical line item values.

### ii. Categorical Columns

In [ ]:
# Total Shipments

print('Total_shipments :',ex_df['Shipment Mode'].value_counts(normalize=True)*100)

* Country	 -- Shipment destination country
* Managed By	-- Organization managing the shipment
* Fulfill Via	  -- Fulfillment method
* Shipment Mode	-- Shipping type (Air, Sea, etc.)
* PQ First Sent to Client Date	-- Request sent to client
* PO Sent to Vendor Date	-- Order sent to vendor
* Scheduled Delivery Date	-- Planned delivery date
* Delivered to Client Date	-- Actual delivery date
* Delivery Recorded Date	-- Date delivery was recorded
* Line Item Quantity	-- Quantity of items shipped
* Line Item Value	-- Total order value
* Weight (Kilograms)	-- Shipment weight
* Freight Cost (USD)	-- Shipping cost
* Vendor	Vendor -- supplying items
* Line Item Insurance (USD)	-- Insurance cost

# 1. Univariate analysis :
* Univariate analysis means analyzing one column of the dataset to understand its values and distribution.

In [ ]:
ex_df.columns

In [ ]:
## Country Distribution

In [ ]:

sns.countplot(x='Country', data=ex_df)

plt.title("Count of Shipments by Country")
plt.xlabel("Country")
plt.ylabel("Number of Shipments")

plt.xticks(rotation=90)

plt.show()

In [ ]:
top10 = ex_df['Country'].value_counts().head(10).index

sns.countplot(x='Country', data=ex_df, order=top10)

plt.title("Count of Shipments by Country")
plt.xlabel("Country")
plt.ylabel("Number of Shipments")

plt.xticks(rotation=90)
plt.show()

In [ ]:
## Shipment Mode distribution

In [ ]:
shipment_mode_counts = ex_df['Shipment Mode'].value_counts()

plt.pie(shipment_mode_counts,
        labels=shipment_mode_counts.index,
        autopct='%.0f%%',
        startangle=90)

plt.title("Shipment Mode Distribution")
plt.show()

## average Freight Cost

In [ ]:
clean_ex_df['Freight Cost (USD)'].mean()

sns.histplot(x='Freight Cost (USD)', data=clean_ex_df,kde=True, bins=30)

plt.tight_layout()
plt.show()

In [ ]:
## Vendor Distribution

In [ ]:
top_vendors = ex_df['Vendor'].value_counts().head(10).index

sns.countplot(x='Vendor', data=ex_df, order=top_vendors)

plt.xticks(rotation=90)
plt.title("Top 10 Vendors by Shipment Count")
plt.show()

In [ ]:
## Freight Cost Distribution

In [ ]:
sns.histplot(clean_ex_df['Freight Cost (USD)'])
plt.xlim(0,60000)
plt.show()

In [ ]:
## Shipment Weight Distribution

In [ ]:
sns.histplot(clean_ex_df['Weight (Kilograms)'])
plt.show()

In [ ]:
## Line Item Value Distribution

In [ ]:
sns.histplot(clean_ex_df['Line Item Value'],kde=True)
plt.show()

In [ ]:
sns.boxplot(x=clean_ex_df['Line Item Value'])